// import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */
// for(let i=0;i<10;i++){
//   console.log(uuid(),i)
// }
export const users = [
  {
    _id: "6a6b43f2-b6dd-47f2-ba43-625b6ee2a707",
    firstName: "Sangeetha",
    lastName: "Jula",
    username: "sangeetha@gmail.com",
    password: "1234",
    userHandler:"sangeethajula",
    userImage:"https://res.cloudinary.com/chirpssocialmediaapp/image/upload/v1687212774/social-media/avatarteddy.jpg",
    link:"https://sangeethajportfolio.netlify.app/",
    bio:"neograd 2023, software Developer",
    userTheme:"https://res.cloudinary.com/chirpssocialmediaapp/image/upload/v1687456655/backgrondTheme.avif",
    dateOfBirth:"13 April 2021",
    followers:[],
    following:[],
    bookmarks:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "736c42b4-8fb6-406e-be84-be1e33b000ea",
    firstName: "Sandeep",
    lastName: "Jula",
    username: "sandyJula@gmail.com",
    password: "1234",
    userHandler:"sandeepsandy",
    userImage:"https://res.cloudinary.com/chirpssocialmediaapp/image/upload/v1687211121/docs/leonardo.webp",
    link:"",
    bio:"Senior Testor, cricket lover",
    userTheme:"https://res.cloudinary.com/chirpssocialmediaapp/image/upload/v1687456655/backgrondTheme.avif",
    dateOfBirth:"21 June 1995",
    followers:[],
    following:[],
    bookmarks:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "f1e8067b-27ba-42ea-9ce2-d4879e530438",
    firstName: "simons",
    lastName: "Cat",
    username: "simon@gmail.com",
    password: "1234",
    userHandler:"simonscat",
    userImage:"https://res.cloudinary.com/chirpssocialmediaapp/image/upload/v1687212774/social-media/avatarteddy.jpg",
    link:"https://simonscatpetstore.com",
    bio:"Animal Lover, check out my simons cat pet store ,😺",
    userTheme:"https://res.cloudinary.com/chirpssocialmediaapp/image/upload/v1687456655/backgrondTheme.avif",
    dateOfBirth:"13 April 1975",
    followers:[],
    following:[],
    bookmarks:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "e649c2e1-40a4-40e6-bb58-66e7264fc411",
    firstName: "Yoongi",
    lastName: "min",
    username: "AgustDTBTS@gmail.com",
    password: "1234",
    userHandler:"suga",
    userImage:"https://res.cloudinary.com/chirpssocialmediaapp/image/upload/v1687168370/docs/minyoongi.webp",
    link:"https://sangeethajportfolio.netlify.app/",
    bio:"rapper, suga of BTS ,Loves Army 💜 and Music 💓",
    userTheme:"https://res.cloudinary.com/chirpssocialmediaapp/image/upload/v1687456655/backgrondTheme.avif",
    dateOfBirth:"08 march 1993",
    followers:[],
    following:[],
    bookmarks:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "7ee6fe47-aada-40aa-8318-929662170636",
    firstName: "Aria",
    lastName: "Holmes",
    username: "AriaHolmes@gmail.com",
    password: "1234",
    userHandler:"ariaholmes",
    userImage:"https://res.cloudinary.com/chirpssocialmediaapp/image/upload/v1687211423/docs/aria.avif",
    link:"",
    bio:"software Developer, insta Influencer, loves Life ",
    userTheme:"https://res.cloudinary.com/chirpssocialmediaapp/image/upload/v1687456655/backgrondTheme.avif",
    dateOfBirth:"13 April 2000",
    followers:[],
    following:[],
    bookmarks:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "c53f18ce-6760-4d61-8032-8c0e5926ab2e",
    firstName: "sravani",
    lastName: "Bhupati",
    username: "sravaniBhupati@gmail.com",
    password: "1234",
    userHandler:"sravs",
    userImage:"https://res.cloudinary.com/chirpssocialmediaapp/image/upload/v1687094072/cld-sample.jpg",
    link:"",
    bio:"IT industry, Food Lover, Love My country",
    userTheme:"https://res.cloudinary.com/chirpssocialmediaapp/image/upload/v1687456655/backgrondTheme.avif",
    dateOfBirth:"15 Dec 1999",
    followers:[],
    following:[],
    bookmarks:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "0b73d84b-0605-4c9c-9d99-243252299056",
    firstName: "Elon",
    lastName: "Musk",
    username: "TelonMusk@gmail.com",
    password: "1234",
    userHandler:"Elon",
    userImage:"https://res.cloudinary.com/chirpssocialmediaapp/image/upload/v1687458120/elonmusk.jpg",
    link:"https://www.tesla.com/elon-musk",
    bio:"CEO of twitter, co-founded and leads Tesla 🚙, SpaceX 🚀, Neuralink 🧠 and The Boring Company.",
    userTheme:"https://res.cloudinary.com/chirpssocialmediaapp/image/upload/v1687458317/spacextheme.jpg",
    dateOfBirth:"28 June 1971",
    followers:[],
    following:[],
    bookmarks:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "84380cb5-0627-4df2-a2a2-49f4644497ff",
    firstName: "Navya",
    lastName: "Dwivedi",
    username: "navyaD@gmail.com",
    password: "1234",
    userHandler:"Sweety",
    userImage:"https://res.cloudinary.com/chirpssocialmediaapp/image/upload/v1687459883/defaultprofile.png",
    link:"",
    bio:"UnderGrad Student ,Looking for Intership in tech background",
    userTheme:"https://res.cloudinary.com/chirpssocialmediaapp/image/upload/v1687456655/backgrondTheme.avif",
    dateOfBirth:" 08 November 2003",
    followers:[],
    following:[],
    bookmarks:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "f0a5f795-ba7a-4f9a-ab1f-fa0eb90c95da",
    firstName: "sunil",
    lastName: "Chhetri",
    username: "sunil@gmail.com",
    password: "1234",
    userHandler:"chhetri",
    userImage:"https://res.cloudinary.com/chirpssocialmediaapp/image/upload/v1687212774/social-media/avatarteddy.jpg",
    link:"https://www.instagram.com/chetri_sunil11/",
    bio:"My life revolves around shuttling between taking the field for India and @bengalurufc. Couldn't have had it better",
    userTheme:"https://res.cloudinary.com/chirpssocialmediaapp/image/upload/v1687456655/backgrondTheme.avif",
    dateOfBirth:"13 April 2021",
    followers:[],
    following:[],
    bookmarks:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];
